services:
  - type: web
    name: project-amazonia
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt && chmod +x build.sh && ./build.sh"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: 0
      - key: OPENAI_API_KEY
        sync: false

  - type: pserv
    name: project-amazonia-db
    env: docker
    plan: free
    region: oregon
    ipAllowList: []
